### ISSUE TITLE
npm install is not working

### ISSUE THREAD

**Issue by HK-Zhang** [remy/jsconsole#127]
I got below error when running npm install on windows 10. 

> @remy/jsconsole@2.1.2 prepare D:\VerIT\Demo\jsconsole\jsconsole
> npm run lib

> @remy/jsconsole@2.1.2 lib D:\VerIT\Demo\jsconsole\jsconsole
> rm -rf dist; npm run styles; NODE_ENV=production babel src/core --out-dir dist --copy-files --ignore '__tests__'

rm: unknown option -- out-dir
Try 'rm --help' for more information.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @remy/jsconsole@2.1.2 lib: `rm -rf dist; npm run styles; NODE_ENV=production babel src/core --out-dir dist --copy-files --ignore '__tests__'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @remy/jsconsole@2.1.2 lib script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by HK-Zhang** [comment]
It is working in linux

**Comment by oliverfoster** [comment]
In Windows, you'll need [git for windows](https://git-scm.com/download/win) and to configure npm scripts to run using bash.exe rather than cmd.exe with [something like this](https://stackoverflow.com/questions/23243353/how-to-set-shell-for-npm-run-scripts-in-windows#answer-46006249) 

`$ npm config set script-shell "bash"`

`$ git clone` then `$ npm start` should work to get the development site running.

At the moment the site gives a breaking linting error [on this line](https://github.com/remy/jsconsole/blob/master/src/core/lib/internal-commands.js#L40). So just replace with single quotes:
```js
    if (url === 'datefns') url = 'date-fns'; // Backwards compatibility
```
Then, weirdly, `package.json:scripts.build` doesn't like the `PUBLIC_URL=/` value, bash/node seems to change it to `PUBLIC_URL=C:/Program Files/git/` at runtime, so changing the value to `PUBLIC_URL=//` solves the issue.

Then to run the server properly:

`$ npm run build`
`$ node lib/app.js`
