### ISSUE TITLE
Cannot "type" symbols from Palm Pre SYM menu

### ISSUE THREAD

**Issue by rwaldron** [remy/jsconsole#4]
The only way to use {} is from the SYM menu. Selecting any symbols from the menu does nothing.

**Comment by remy** [comment]
Sorry Rick, I'm going to close this. I realise you've been waiting for my response over the last seven years, and in fact whole human beings have been born across the globe since this rather unimpressive responsive. *Even* Palm Pre don't exist…went the way of the dinos…maybe. Anyway, love to you and your family ❤️
